exclude: "^semgrep/tests/e2e/(targets|snapshots)|semgrep-core/tests|.*\\.md"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^semgrep/tests/.+$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.782"
    hooks:
      - id: mypy
        exclude: ^semgrep\/tests\/.+$|^setup.py$|^scripts\/.+$$
        args: [--config, mypy.ini]
      - id: mypy
        alias: mypy-test
        name: mypy (test files)
        files: ^semgrep\/tests\/.+$
        args: [--config, mypy-tests.ini]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==20.1.4"]
        args: ["--select=B,E9,F63,F7,F82"]

  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.18.0'
    hooks:
      - id: semgrep
        name: Semgrep Python
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ['--config', 'https://semgrep.dev/p/python', '--error']
      - id: semgrep
        name: Semgrep Bandit
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ['--config', 'https://semgrep.dev/p/bandit', '--error']
      - id: semgrep
        name: Semgrep Local
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        # Managed at https://semgrep.dev/mschwager:semgrep-local
        args: ['--config', 'https://semgrep.dev/mschwager:semgrep-local', '--error']

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.7.1
        files: "[.]sh$"

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        files: "Dockerfile"
        entry: hadolint/hadolint:v1.18.0 hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL3018"]


  # Run develop semgrep. Only used in CI
  # To run locally use `pre-commit run --hook-stage manual semgrep-docker-develop`
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.18.0'
    hooks:
      - id: semgrep-docker-develop
        name: Semgrep Develop Python
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ['--config', 'https://semgrep.dev/p/python', '--error']
        stages: [manual]
      - id: semgrep-docker-develop
        name: Semgrep Develop Bandit
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        args: ['--config', 'https://semgrep.dev/p/bandit', '--error']
        stages: [manual]
      - id: semgrep-docker-develop
        name: Semgrep Develop Local
        types: [python]
        exclude: "^semgrep/tests/.+$|^scripts/.+$|^semgrep/setup.py$"
        # Managed at https://semgrep.dev/mschwager:semgrep-local
        args: ['--config', 'https://semgrep.dev/mschwager:semgrep-local', '--error']
        stages: [manual]
